### ISSUE TITLE
ROS Error : Failed to send message

### ISSUE THREAD

**Issue by Prj1508** [ros-industrial/ros_canopen#365] opened 2019-12-05 12:59 UTC
I get this message when I publish on sent_messages topic of socketcan_bridge node. I see that this is getting published properly, but is not being sent to the can bus ( topic to socketcan issue). CAN is working properly and I can see traffic thru candump. 

In topic to socketcan code, I see that there is a boolean flag which sends this message when fault. Is this to do with overflow of data I am trying to stuff into available data bits of the message

I am using Ubuntu 16.04 and ROS Kinetic

thanks for your help

**Comment by mathias-luedtke** [comment] 2019-12-09 14:51
I would suspect that your frame is not valid.
How do you publish the data?

**Comment by Prj1508** [comment] 2019-12-09 17:27
i am publishing thru a 10ms timer callback. All CAN data byte stuffing is happening in another subscriber call back which updates a global variable of type can_msgs::Frame. This variable is then published thru a 10ms timer callback.

**Comment by Prj1508** [comment] 2019-12-09 17:29
this issue is same as #366.

**Comment by Prj1508** [comment] 2019-12-09 17:30
I didn’t not capture console output with —screen option. will do so today and revert

**Comment by mathias-luedtke** [comment] 2019-12-09 17:36
> this issue is same as 306.

306 or 366?

**Comment by Prj1508** [comment] 2019-12-09 18:06
Sorry, 366

**Comment by mathias-luedtke** [comment] 2019-12-09 19:15
duplicate of #366

**Closed as completed by mathias-luedtke** 2019-12-09 19:15 UTC
Labels: question
