### ISSUE TITLE
Can device goes into an error state and the socketcan node never recovers

### ISSUE THREAD

**Issue by akashmod** [ros-industrial/ros_canopen#468] opened 2022-09-01 18:08 UTC
We have noticed that the can communication drops off sometimes because the socketcan node goes into an error state, if the driver goes into an error state and never recovers even if the driver is back online. Respawning the node solves the issue, which makes us believe that the issue is in the node itself.

**Comment by mathias-luedtke** [comment] 2022-09-17 12:53
If you are talking about the socketcan_bridge node, then this is a duplicate of https://github.com/ros-industrial/ros_canopen/issues/244.
The other nodes have a `recover` service..

**Closed as completed by mathias-luedtke** 2022-09-17 12:53 UTC
