### ISSUE TITLE
How to connect ros_canopen with Moveit! Action

### ISSUE THREAD

**Issue by CShaohn** [ros-industrial/ros_canopen#411] opened 2020-11-28 13:37 UTC
Hi,all,
I would like to use MoveIt! to control my robot,but seem my move_group and ros_canopen have not really conection.how to use ros_canopen as the action service of Moveit!.Could you please tell me what should I do?

![Imgur](https://imgur.com/IV4VZtC.jpg)

`[ERROR] [1606569545.900921745]: Unable to identify any set of controllers that can actuate the specified joints: [ I1_Joint T2_Joint T3_Joint i4_Joint t5_Joint ]
[ERROR] [1606569545.900959504]: Known controllers and their joints:

[ INFO] [1606569545.925825528]: ABORTED: Solution found but controller failed during execution`

**Comment by mathias-luedtke** [comment] 2020-11-30 08:37
It looks like you did not initialize the driver with the `init` service (see [ROS wiki](http://wiki.ros.org/canopen_chain_node#Services)).

Since this is not a bug or feature request, I will close this issue.
You may find further information and help on [ROS answers](https://answers.ros.org/).

**Closed as completed by mathias-luedtke** 2020-11-30 08:37 UTC
Labels: question
