### ISSUE TITLE
next release?

### ISSUE THREAD

**Issue by gavanderhoorn** [ros-industrial/ros_canopen#192] opened 2016-10-18 11:56 UTC
More of a question, but I was wondering if/when the next release is planned? 0.6.4 is already more than a year old, and there appear to be quite some updates that are only found in the sources at the moment.

**Comment by gavanderhoorn** [comment] 2016-10-18 11:57
I'm aware of #161. I'm specifically asking about Indigo.

**Comment by mathias-luedtke** [comment] 2016-10-18 12:13
(duplicate of #189)

I don't have much time for testing right now.
I could release the current state (as it is running on Care-O-bot 4), but without the missing issue.

**Comment by gavanderhoorn** [comment] 2016-10-18 12:16
I hadn't seen #189, my apologies.

I'll be the last to bug other devs about releases, but would there be much difference between users reporting bugs about _from source_ builds versus a released build?

**Comment by viktorvorobev** [comment] 2016-10-25 10:26
I'm sorry, will there be any release for kinetic? I understand that there is some issues with ros_control, but still?

**Comment by mathias-luedtke** [comment] 2016-10-29 09:53
> I'm sorry, will there be any release for kinetic? I understand that there is some issues with ros_control, but still?

A jade/kinetic release can be triggered after https://github.com/ros-industrial/ros_canopen/issues/161.
However, I cannot work on it right now.

**Comment by mathias-luedtke** [comment] 2016-12-10 23:07
just released for indigo.
jade will follow after I was able to test it myself.
same for kinetic, but it's more complicated to test (still on 14.04).

**Comment by gavanderhoorn** [comment] 2016-12-11 08:55
Very nice. Thanks for the effort.

Would you prefer to track jade/kinetic releases in a separate issue?

**Comment by mathias-luedtke** [comment] 2016-12-11 10:14
"Next release" is a nice reminder ;)
The jade and kinetic releases are tracked in https://github.com/ros-industrial/ros_canopen/milestone/4 and https://github.com/ros-industrial/ros_canopen/milestone/5

**Comment by mathias-luedtke** [comment] 2016-12-13 09:50
Jade release triggered: https://github.com/ros/rosdistro/pull/13399

**Comment by mathias-luedtke** [comment] 2016-12-21 16:02
kinetic is released as well.
(https://github.com/ros/rosdistro/pull/13424)

**Comment by gavanderhoorn** [comment] 2016-12-21 16:20
Awesome! :sparkles: :hamburger: :beers:

**Comment by mathias-luedtke** [comment] 2016-12-29 17:41
I will close this issue after the next wave of releases

**Comment by mathias-luedtke** [comment] 2017-03-20 19:08
Released again for indigo to kinetic :)

**Closed as completed by mathias-luedtke** 2017-03-20 19:08 UTC
Labels: question
